Failsafecleanup (oblong) (#47)
* chore: small failsafe cleanup

* fix: `TypeError: Cannot find function #reason in object class_2739`

* fix: velocity failsafe fire issues && fix: remove bandaid for teleport failsafe

* fix: falling triggering velocity failsafe (cooked code)

* allow aspect of the leech (just change to 'aspect of the')

* oop

---------

Co-authored-by: oblongboot <dontemailme@stop.com>
Co-authored-by: oblongboot <81798709+oblongboot@users.noreply.github.com>